//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int IdAnimal { get; set; }
        public string NombreEspecie { get; set; }
        public double PesoPromedio { get; set; }
        public int EdadPromedio { get; set; }
        public int IdTipoAnimal { get; set; }
    
        public virtual TipoAnimal TipoAnimal { get; set; }
    }
}
